[package]
name = "spotify2media_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
rfd = "0.14.1"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"
csv = "1.3.0"
regex = "1.10.4"
anyhow = "1.0.86"
lofty = "0.18.0"
directories = "5.0.1"
rayon = "1.10.0"